### PR TITLE
resource/acl: add a few missing options

### PR DESCRIPTION
**Pull request by svanharmelen**

### CODE REVIEW

**Comment by cattywampus** [comment]
Hi @svanharmelen, I'm working with @mobilederek to test your changes. Sorry we haven't had a chance to get to it until recently. I was able to build the provider in Linux. I performed the following steps to test it:

1. Create a basic plan with one ACL and one rule - deny all
2. Test that plan with the previous build of the terraform-provider-ciscoasa (without these PR changes) - works ✅ 
3. Update rule with position and remarks
3. Run the modified plan with the new build of the provider - doesn't work ❌ 

The error message I get is:
```
ciscoasa_acl.acl: Error create ACE on ACL <acl name goes here>: <some integer>
```

I ran the apply command with `TF_LOG=DEBUG` enabled and I don't see anything revealing in that output. I would provide that in a gist but I'd have to get it redacted and approved first. It shows the modification that it's about to perform (sets active to false, clears the fields, and creates a new rule with the correct values) and fails immediately with that message and no other context or information about failure.

**Comment by svanharmelen** [comment]
Hi @cattywampus! Could you maybe try it again, but then first clear the existing ACL entries so the ACL is empty?

My initial thoughts are that the new entry collides with the existing one.

I’m not behind a desk until Monday, so cannot have a closer look before that. But will check the code and follow up early next week.

**Comment by cattywampus** [comment]
I destroyed the old ACL and recreated it using the new build of the ciscoasa provider and it works. I still need to verify the positions are correct, but the remarks are there. I'll let you know as soon as I'm done testing it.

**Comment by cattywampus** [comment]
After some initial testing with Derek, here's what we've observed:

* When I set positions and remarks on an ACL with multiple rules, those positions appear to be respected by the cisco-asa. ✔️ 
* If I create an ACL and then try to modify the `position`, `remarks` or `log_status` attribute for any of the rules in that ACL, I get an error: ❌ 
    `ciscoasa_acl.acl: Error creating ACE on ACL <acl name>: 1676631835`
    I'm not sure how important this use case is. I need to talk to the networking team more to understand if this is something they would ever possibly need to do. It's possible my testing scenarios are an unrealistic usage of a cisco-asa since I don't have much experience with that. 
* If I create an ACL and then try to modify the `destination_service`, the changes are sent to the cisco-asa however the rule that was modified now appears at the end of the position ordered list. So it appears that it's position isn't being enforced when that particular attribute is updated. ❌ 
* When setting `log_status` the assigned value shows up for the rule when checking on the cisco-asa. ✔️  
* However, when I set `log_status` on a deny rule that I wanted to appear at the bottom of my position-ordered list of rules, that particular rule showed up as the second rule, instead of the last one. ❌ 
    Setting `log_status` on rules that were **not deny** seemed to maintain their position in the ordered list of rules. The position value we used for the deny rule was a large integer (987654) and all of the other rules were orders of magnitude smaller (100, 200, 300) in position. 

Here's the sample ACL terraform plan I was testing with:

```
#Extended ACL starts here

resource "ciscoasa_acl" "acl" {
  name = "test_acl_access_in"
  managed = "true"
  rule {
    source = "0.0.0.0/0"
    destination = "1.1.1.1/32"
    destination_service = "tcp/10443"
    position = 300
    remarks = ["Yeah! web...", "should be at pos 300"]
    log_status = "Informational"
  }
  rule {
    source = "0.0.0.0/0"
    destination = "1.1.1.1/32"
    destination_service = "tcp/443"
    position = 100
    remarks = ["Let's be safe", "should be at pos 100"]
  }
  rule {
    source = "1.2.3.4/32"
    destination = "9.9.9.9/32"
    destination_service = "tcp/22"
    position = 1
    remarks = ["I'm first!", "should be position 1"]
  }
  rule {
    source = "0.0.0.0/0"
    destination = "0.0.0.0/0"
    destination_service = "ip"
    permit = "false"
    position = 987654
    remarks = ["You shall not pass!", "should be at pos 987654"]
    log_status = "Informational"
  }

```

**Comment by svanharmelen** [comment]
I have a feeling how to fix this, will try to make some time later today...

**Comment by svanharmelen** [comment]
@cattywampus @mobilederek I just had some time to test with this again and updated the code a bit. Would be great if you can give the updated code another test run to see if the problems are solved now.

**Comment by cattywampus** [comment]
Awesome, thank you! We'll pull down the changes and test it today.

**Comment by mobilederek** [comment]
Sorry for the delay. Our priorities got shuffled last week. We're planning to do more testing today.

**Comment by cattywampus** [comment]
Hi @svanharmelen 

Yes, sorry for the delayed turnaround. I had some difficulty with the positioning at first, but I recently discovered that using position values in large increments isn't working. Once I switched to incrementing positions by 1, my ace rules started showing up in the right order. I'm going to continue to keep an eye on that to make sure it stays consistent.

The failures above appear to be working well. Updating fields doesn't seem to trigger the ACE / ACL error I provided. Also, the deny rule appears to be holding it's own much better at the end of the acl. 

We'll be using this a lot more of the course of the next week, so it's likely we might have some other feedback.

I did run across one peculiar situation where I was managing multiple ACL's in the same terraform project / state file. Once of these ACL's had an error in it (invalid source). However it created the other ACLs fine. When I try to destroy (or plan or apply) new changes to the project, I get an error saying RECORD-NOT-FOUND for the ACL failed to be created. From what I can tell, it's the same error message if you try to GET an api endpoint that doesn't exist (404). So it looks like the terraform provider is reaching out to the device to capture what all of the ACL's are. It fails on this step even before it prompts the user to enter `yes` to run `terraform apply`. This initially led me to think it was a syntax issue in my HCL, but that is not the case. `TF_LOG=DEBUG` shows it is failing to find the ACL in question on the device. 

So this left things in a weird state where I can run the terraform plans because of the error I'm getting before it has a chance to kick off anything. We're going to delete the extended acl's on the device and blow away the state file to start over. But it makes me wonder if we are going to run into a concern with modifying our firewall plans, expecting users to introduce breaking failures.

I don't have instructions for reproducing this yet, but if I'm able to make it happen again I will send you as much information as I can.

**Comment by svanharmelen** [comment]
Hi @cattywampus, thanks for the feedback and good to hear that things look better now!

I think that issue might be something we have seen before, but hopefully @rtnh can confirm that? If it's indeed the same issue (or has the same root cause) then we already have an open case for that with Cisco (yet they don't seem to be very actively working on a fix 😞).

If it looks the same, maybe you can share the case details @rtnh? Then maybe @cattywampus or @mobilederek can try to give our friends at Cisco a gentle nudge as well 😏

**Comment by cattywampus** [comment]
We are definitely going to be nudging Cisco about several things, starting with access to their API docs. It's interactive and doesn't work air-gapped. We're seeing some other interesting issues (which I'll detail below) so my plan is to remove terraform from the picture and test the API in isolation to see if this is something they need to resolve or if it's something we can fix / handle in the terraform provider. Here's what we're seeing.

* __modifying acls messes up the positioning order__ - When we create a new acl using the latest code you provided, the positions appear to be working. However, if we modifying any existing rule in the created acl or add a new rule we start to see the positions of rules not reflect the values we explicitly assigned in the HCL tf file. 

* __terraform recreates / updates ACL's with no changes__ - If we create a new ACL using `terraform apply`, then modify *nothing* and run `terraform apply` a second time it looks like terraform is recreating all of the rules. Here's a snippet of what I see:

  ```
  ~ ciscoasa_acl.acl2
      rule.2813438316.active:              "" => "true"
      rule.2813438316.destination:         "" => "192.168.1.1/32"
      rule.2813438316.destination_service: "" => "tcp/https"
      rule.2813438316.id:                  "" => <computed>
      rule.2813438316.log_interval:        "" => "300"
      rule.2813438316.log_status:          "" => "Default"
      rule.2813438316.permit:              "" => "true"
      rule.2813438316.position:            "" => ""
      rule.2813438316.remarks.#:           "0" => "0"
      rule.2813438316.source:              "" => "172.0.31.6/32"
      rule.2813438316.source_service:      "" => ""
      rule.2972375698.active:              "true" => "false"
      rule.2972375698.destination:         "192.168.1.1/32" => ""
      rule.2972375698.destination_service: "tcp/443" => ""
      rule.2972375698.log_interval:        "300" => "0"
      rule.2972375698.log_status:          "Default" => ""
      rule.2972375698.permit:              "true" => "false"
      rule.2972375698.position:            "0" => "0"
      rule.2972375698.remarks.#:           "0" => "0"
      rule.2972375698.source:              "172.0.31.6/32" => ""
      rule.2972375698.source_service:      "" => ""
  ```
  Here you can see the existing rule is being cleared out, set to `""` and a new rule with the exact same settings is being created. 

My next steps are to test the API directly to see how many of these issues I can recreate directly on the device and bug the folks at Cisco to help us fix. If you think these two issues might be solvable in Terraform, I would be happy to help you implement and test any changes that need to be made. I'm currently lacking in Go-fu but it doesn't look insurmountable. Just need some guidance to understand how to navigate terraform plugins. 

Regarding the `RESOURCE-NOT-FOUND` error, I was wondering if that's something we could handle by catching an exception. In situations where somethings don't exist like this we get into a weird state because terraform thinks it should exist. So maybe the state object is being created prematurely before the API kicks back the original error (i.e., invalid source).

**Comment by rtnh** [comment]
@svanharmelen it seems that bug has been fixed in more recent releases of the api agent.
Or at the very least it's not listed as open anymore.
The list of open and resolved bugs can be found in the release notes:
https://www.cisco.com/c/en/us/td/docs/security/asa/api/13/asa-api-rn-13.html

CSCvf50673 was opened to resolve our case. Since then it has been linked to a couple of other bugs which probably share the same underlying problem. You'll need a Cisco account to look at the details.

**Comment by svanharmelen** [comment]
Thanks for the info/update @rtnh!

**Pull request merged**
